# Introduction

The automotive landscape is undergoing a profound shift towards sustainable and eco-friendly transportation, and at the forefront of this evolution is the increasing adoption of electric vehicles (EVs). Washington, as a state actively embracing this change, provides an ideal viewpoint for our investigation. The emergence and development of electric vehicles not only have a significant impact on the automotive market but also bring changes to environmental sustainability, infrastructure development, and the entire automotive industry. Our objective is to contribute to the analysis of the electric vehicle market in Washington State, enriching the discussion on sustainable mobility based on the electric vehicle population dataset in WA.

**Questions of Interest:**

-   Trends in Electric Vehicle Adoption

    -   What patterns and trends characterize the adoption of electric vehicles in Washington state over the years?
    -   Are the patterns and trends the same for both plug-in hybrid electric vehicle (PHEV) and battery electric vehicle (BEV)?
    -   How does EVs distribute across Washington State? Are there similar number of EVs in each county?

-   Popular Electric Vehicle Makes/ Models

    -   Which electric vehicle brands (makes) and models have gained prominence in Washington state?
    -   Does consumer preference align with certain characteristics, such as brand reputation?
    -   Do people in different counties have the same preference?
    -   Are the popular brands different for PHEV and BEV?

-   Price Analysis

    -   How is the base Manufacturer's Suggested Retail Price (MSRP) distributed among the electric vehicles?
    -   Is the distribution the same for BEV and PHEV?
    -   What is the relationship between the base MSRP and other features, such as electric range?

-   Distribution of Electric Range

    -   How is the electric range distributed among the electric vehicles?
    -   Is it correlated with EV type? Is it different for PHEV and BEV?
